name: RPS
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.26
  - libsqlite=3.45.1
  - libzlib=1.2.13
  - numpy=1.26.4
  - openssl=3.2.1
  - pandas=2.2.1
  - pip=24.0
  - python=3.10.13
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - setuptools=69.1.1
  - six=1.16.0
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.42.0
  - xz=5.2.6
